spring.application.name=book
logging.level.org.springframework.boot.context.config=DEBUG

# Initialize schema (optional)
spring.sql.init.mode=always

spring.profiles.active=dev

# Logging configuration
logging.level.root=INFO
logging.level.com.mtn=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

