spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book
    username: postgres
    password: Georgie4u
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
