server.port=8080
# Initialize schema
spring.sql.init.mode=always

spring.r2dbc.url=${DB_URL}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

jwt.secret=f3c8b1e4d79a42cb8e7ac4fda12bf94e2e6b5ddc3a7f49e1c2d8a7e3b5c9f1a49d7c4b2fa8e1d6c3b4f9a2e7c1d84b7fa12c9e6d5b7f4c8d3a9b7e1c6f5d3b2a
jwt.expiration=86400000



spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30000

logging.level.io.r2dbc.postgresql=INFO
logging.level.org.springframework.r2dbc.core=DEBUG
logging.level.reactor.core.publisher=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# Logging configuration
logging.level.root=INFO
logging.level.com.mtn=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# Netty configuration
server.netty.max-initial-line-length=4096



springdoc.api-docs.path=/api-docs

app.cors.allowed-origins=*


